[env:waveshare-esp32-s3-touch-lcd-183]
board = waveshare-esp32-s3-touch-lcd-183
board_build.partitions = support_files/custom_16Mb.csv
build_src_filter = ${env.build_src_filter} +<../boards/waveshare-esp32-s3-touch-lcd-183>
build_flags =
    ${env.build_flags}
    -Iboards/waveshare-esp32-s3-touch-lcd-183
    -DBOARD_HAS_PSRAM=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DWAVESHARE_ESP32_S3_TOUCH_LCD_183=1
    -DHAS_1_BUTTONS=1
    -DHAS_DISCRETE_INPUT=1
    -DFIXED_PORTRAIT=1
    -DROTATION=0
    -DHAS_BTN=1
    -DSEL_BTN=0
    -DUP_BTN=-1
    -DDW_BTN=-1
    -DBTN_ACT=LOW
    -DBTN_ALIAS='"BOOT"'
    -DMINBRIGHT=1
    -DBACKLIGHT=40
    -DST7789_DRIVER=1
    -DUSER_SETUP_LOADED
    -DTFT_RGB_ORDER=TFT_BGR
    -DTFT_WIDTH=240
    -DTFT_HEIGHT=284
    -DTFT_COL_OFS1=0
    -DTFT_ROW_OFS1=0
    -DTFT_COL_OFS2=0
    -DTFT_ROW_OFS2=0
    -DTFT_MISO=-1
    -DTFT_MOSI=7
    -DTFT_SCLK=6
    -DTFT_CS=5
    -DTFT_DC=4
    -DTFT_RST=38
    -DTFT_BL=40
    -DTFT_BACKLIGHT_ON=HIGH
    -DGFX_BL=40
    -DTFT_IPS=1
    -DSPI_FREQUENCY=40000000
    -DSPI_READ_FREQUENCY=20000000
    -DLOAD_GLCD=1
    -DLOAD_FONT2=1
    -DLOAD_FONT4=1
    -DLOAD_FONT6=1
    -DLOAD_FONT7=1
    -DTOUCH_SDA=15
    -DTOUCH_SCL=14
    -DTOUCH_RST=39
    -DTOUCH_INT=13
    -DTOUCH_ADDR=0x15
    ; Official schematic SD-CARD block: independent SPI bus, VCC3V3 rail.
    -DSDCARD_MOSI=1
    -DSDCARD_SCK=2
    -DSDCARD_MISO=3
    -DSDCARD_CS=42
lib_deps =
    ${env.lib_deps}
