name: Waveshare 1.83 Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-waveshare-183:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true
      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      - name: Install PlatformIO
        run: pip install platformio requests esptool
      - name: Build Waveshare 1.83
        run: platformio run -e waveshare-esp32-s3-touch-lcd-183
      - name: Upload binaries
        uses: actions/upload-artifact@v6
        with:
          name: waveshare-esp32-s3-touch-lcd-183
          path: |
            .pio/build/waveshare-esp32-s3-touch-lcd-183/*.bin
          if-no-files-found: error
