name: Waveshare ESP32-S3 1.83 Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: recursive
      - name: Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - name: Install PlatformIO
        run: python -m pip install --upgrade platformio requests esptool
      - name: Build
        run: platformio run -e waveshare-esp32-s3-touch-lcd-183
      - name: Upload firmware
        uses: actions/upload-artifact@v6
        with:
          name: Launcher-Waveshare-ESP32-S3-Touch-LCD-1.83
          path: .pio/build/waveshare-esp32-s3-touch-lcd-183/*.bin
          if-no-files-found: error
